testcd as early as possible before doing too much

diff --git a/debian/live-autoconfig.init b/debian/live-autoconfig.init
--- a/debian/live-autoconfig.init
+++ b/debian/live-autoconfig.init
@@ -456,6 +456,26 @@ esac
 export LANG
 
 ###############################################################################
+# CD Checker
+###############################################################################
+if checkbootparam "testcd" || checkbootparam "testdvd"; then
+	echo " ${BLUE}Checking CD data integrity as requested by '${CYAN}testcd${BLUE}' boot option.${NORMAL}"
+	echo " ${BLUE}Reading files and checking against ${FLL_IMAGE_DIR}/md5sums, this may take a while...${NORMAL}"
+	echo -n "${RED}"
+	( cd /cdrom/ ; rm -f /tmp/md5sum.log ; LANG="$LANG" md5sum -c ${FLL_IMAGE_DIR}/md5sums 2>&1 | tee /tmp/md5sum.log )
+	if [ "$?" = "0" ]; then
+		echo " ${GREEN}Everything looks OK${NORMAL}"
+	else
+		echo "${RED} *** CHECKSUM FAILED FOR THESE FILES:                          ***"
+		egrep -v '(^md5sum:|OK$)' /tmp/md5sum.log
+		echo "${RED} *** DATA ON YOUR CD MEDIUM IS POSSIBLY INCOMPLETE OR DAMAGED, ***${NORMAL}"
+		echo "${RED} *** OR YOUR COMPUTER HAS BAD RAM.                             ***${NORMAL}"
+		echo -n "${CYAN}Hit return to contine, or press the reset button to quit.${NORMAL} "
+		read a
+	fi
+fi
+
+###############################################################################
 # update locale settings
 ###############################################################################
 # ensure that /etc/default/locale is an ordinary file and not a symlink
@@ -838,26 +858,6 @@ update_progress()
 		(echo "progress $1" > /etc/splashy/splashy.fifo) &
 	fi
 }
-
-###############################################################################
-# CD Checker
-###############################################################################
-if checkbootparam "testcd" || checkbootparam "testdvd"; then
-	echo " ${BLUE}Checking CD data integrity as requested by '${CYAN}testcd${BLUE}' boot option.${NORMAL}"
-	echo " ${BLUE}Reading files and checking against ${FLL_IMAGE_DIR}/md5sums, this may take a while...${NORMAL}"
-	echo -n "${RED}"
-	( cd /cdrom/ ; rm -f /tmp/md5sum.log ; LANG="$LANG" md5sum -c ${FLL_IMAGE_DIR}/md5sums 2>&1 | tee /tmp/md5sum.log )
-	if [ "$?" = "0" ]; then
-		echo " ${GREEN}Everything looks OK${NORMAL}"
-	else
-		echo "${RED} *** CHECKSUM FAILED FOR THESE FILES:                          ***"
-		egrep -v '(^md5sum:|OK$)' /tmp/md5sum.log
-		echo "${RED} *** DATA ON YOUR CD MEDIUM IS POSSIBLY INCOMPLETE OR DAMAGED, ***${NORMAL}"
-		echo "${RED} *** OR YOUR COMPUTER HAS BAD RAM.                             ***${NORMAL}"
-		echo -n "${CYAN}Hit return to contine, or press the reset button to quit.${NORMAL} "
-		read a
-	fi
-fi
 
 update_progress 10
 
