Rework cpufreq routine, really try acpi-cpufreq when the detected cpufreq module fails to be loaded.

diff --git a/debian/live-autoconfig.init b/debian/live-autoconfig.init
--- a/debian/live-autoconfig.init
+++ b/debian/live-autoconfig.init
@@ -1676,45 +1676,56 @@ if laptop-detect 2>/dev/null; then
 fi
 
 ###############################################################################
-# powernow detection
+# cpufreq detection
 ###############################################################################
-if ! checkbootparam "nocpufreq" || ! checkbootparam "nopowernow"; then
+if ! checkbootparam "nocpufreq"; then
 	CPUFREQ=
 	CPUSERV=
+
 	# cpufreq detection from ubuntu powernowd, exports `CPUFREQ' on successful detection
 	if [ -f /usr/share/initscripts-sidux-live/cpufreq-detect ]; then
 		. /usr/share/initscripts-sidux-live/cpufreq-detect
 		
-		# fallback to acpi-cpufreq if this is really a laptop
+		# attempt load the detected cpufreq module
+		if [ -n "$CPUFREQ" ]; then
+			if modprobe "$CPUFREQ" 2>/dev/null; then
+				# start cpufreq power services
+				:
+			else
+				unset CPUFREQ
+			fi
+		fi
+		
+		# if this is a laptop, fallback to acpi-cpufreq 
 		if [ -z "$CPUFREQ" ] && [ -n "$IS_LAPTOP" ]; then
-			modprobe acpi-cpufreq 2>/dev/null && CPUFREQ=acpi-cpufreq
+			if modprobe acpi-cpufreq 2>/dev/null; then
+				CPUFREQ=acpi-cpufreq
+			fi
 		fi
 	fi
 
 	# start power management service
 	if [ -n "$CPUFREQ" ]; then
-		if modprobe "$CPUFREQ" 2>/dev/null; then
-			echo -n " ${GREEN}Activating ${YELLOW}${CPUFREQ}${GREEN} CPUfreq management:${NORMAL}"
-			# hack to disable suspend, it currently does not mix with live-mode
-			# kpowersave exposes this problem to unsuspecting users
-			if [ -w /etc/powersave/sleep ]; then
-				sed -i 's/^\(DISABLE_USER_SUSPEND2.*\)=.*$/\1="yes"/' /etc/powersave/sleep
-			fi
-			# start power management, powersaved is given preference
-			if start_service powersaved >/dev/null; then
-				CPUSERV=powersaved
-			elif start_service powernowd >/dev/null; then
-				CPUSERV=powernowd
-			else
-				echo " ${RED}Failed!${NORMAL}"
-			fi
-			# announce the service
-			if [ -n "$CPUSERV" ]; then
-				echo " ${MAGENTA}${CPUSERV}${GREEN}.${NORMAL}"
-				# add service to hwsetup service list
-				if ! grep -q ^$CPUSERV "$HWSETUP_SERVICES" 2>/dev/null; then
-					echo $CPUSERV >>"$HWSETUP_SERVICES"
-				fi
+		echo -n " ${GREEN}Activating ${YELLOW}${CPUFREQ}${GREEN} CPUfreq management:${NORMAL}"
+		# hack to disable suspend, it currently does not mix with live-mode
+		# kpowersave exposes this problem to unsuspecting users
+		if [ -w /etc/powersave/sleep ]; then
+			sed -i 's/^\(DISABLE_USER_SUSPEND2.*\)=.*$/\1="yes"/' /etc/powersave/sleep
+		fi
+		# start power management, powersaved is given preference
+		if start_service powersaved >/dev/null; then
+			CPUSERV=powersaved
+		elif start_service powernowd >/dev/null; then
+			CPUSERV=powernowd
+		else
+			echo " ${RED}Failed!${NORMAL}"
+		fi
+		# announce the service
+		if [ -n "$CPUSERV" ]; then
+			echo " ${MAGENTA}${CPUSERV}${GREEN}.${NORMAL}"
+			# add service to hwsetup service list
+			if ! grep -q ^$CPUSERV "$HWSETUP_SERVICES" 2>/dev/null; then
+				echo $CPUSERV >>"$HWSETUP_SERVICES"
 			fi
 		fi
 	fi
